#!/usr/bin/env python3
# gen-repos.py — 从域规格表产出 data/<域>_repo.rs 仓储文件(按 content_repo 的
# 模式:by_id / insert / update / delete 四件套 + 域内特有查询手写在文件尾部)。
#
# 用法: python3 scripts/gen-repos.py   # 幂等重生成(手写尾段会被保留?否——
#                                       特有查询请写在 service 侧或本表 SPEC
#                                       的 extras 字段)
import os

# 域 → 实体表清单。函数名取表名去前缀(sys_ 去除)。
SPEC = {
    "identity": ["sys_users", "sys_roles", "sys_tenants", "sys_user_credentials", "sys_user_roles", "sys_role_permissions"],
    "dict": ["sys_languages", "sys_dict_types", "sys_dict_entries"],
    "site": ["sites", "site_settings", "navigations", "navigation_items"],
    "social": ["comments", "interaction_counters", "post_likes", "post_watches"],
    "permission": ["sys_menus", "sys_apis", "sys_permission_groups", "sys_permissions"],
    "messaging": ["internal_messages", "internal_message_recipients", "sys_tasks"],
    "misc": ["sys_org_units", "sys_positions", "sys_login_policies", "content_models", "media_assets"],
    "storage": ["files"],
}

HEADER = """//! {title}Repo — the data layer of the {title} domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{{ActiveModelTrait, DatabaseConnection, EntityTrait}};

use crate::state::{{db_status, not_found_status, StatusResult}};
use store::entities::{{{imports}}};
"""

FN = """
pub async fn {fn}_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<{entity}::Model> {{
    {entity}::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("{label}"))
}}

pub async fn insert_{fn}(db: &DatabaseConnection, a: {entity}::ActiveModel) -> StatusResult<{entity}::Model> {{
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}}

pub async fn update_{fn}(db: &DatabaseConnection, a: {entity}::ActiveModel) -> StatusResult<{entity}::Model> {{
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}}

pub async fn delete_{fn}(db: &DatabaseConnection, id: i64) -> StatusResult<()> {{
    {entity}::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}}
"""


def fn_name(table: str) -> str:
    n = table.removeprefix("sys_")
    return n


def main() -> None:
    out_dir = "services/core-service/src/data"
    for domain, tables in SPEC.items():
        imports = ", ".join(tables)
        parts = [HEADER.format(title=domain, imports=imports)]
        for t in tables:
            parts.append(FN.format(fn=fn_name(t), entity=t, label=fn_name(t).replace("_", " ")))
        path = os.path.join(out_dir, f"{domain}_repo.rs")
        with open(path, "w", encoding="utf-8") as f:
            f.write("".join(parts))
        print(f"{domain}_repo.rs: {len(tables)} entities")
    print("done")


if __name__ == "__main__":
    main()
