//! The `api` repository (the reference's api_repo.go).

//! permissionRepo — the data layer of the permission domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_apis;

















// ── domain-specific queries ─────────────────────────────────────────


// ── the sync face's rebuild pipeline ────────────────────────────────

pub async fn apis_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_apis::Model> {
    sys_apis::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("apis"))
}
pub async fn insert_apis(
    db: &DatabaseConnection,
    a: sys_apis::ActiveModel,
) -> StatusResult<sys_apis::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_apis(
    db: &DatabaseConnection,
    a: sys_apis::ActiveModel,
) -> StatusResult<sys_apis::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_apis(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_apis::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// The api row registered for one operation id (the sync face's
/// upsert lookup).
pub async fn apis_by_operation(
    db: &DatabaseConnection,
    operation: &str,
) -> StatusResult<Option<sys_apis::Model>> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _};
    sys_apis::Entity::find()
        .filter(sys_apis::Column::Operation.eq(operation))
        .one(db)
        .await
        .map_err(db_status)
}
/// The enabled apis, ordered by operation id.
pub async fn apis_enabled_by_operation(
    db: &DatabaseConnection,
) -> StatusResult<Vec<sys_apis::Model>> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _, QueryOrder as _};
    sys_apis::Entity::find()
        .filter(sys_apis::Column::Status.eq("ON"))
        .order_by_asc(sys_apis::Column::Operation)
        .all(db)
        .await
        .map_err(db_status)
}
