//! The `comment` repository (the reference's comment_repo.go).

//! socialRepo — the data layer of the social domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::comments;

// ── Interaction purge/recount helpers (the reference's
//    adjustCounterRow / purge / reset tail of interaction_repo.go) ────

pub async fn comments_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<comments::Model> {
    comments::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("comments"))
}
pub async fn insert_comments(
    db: &DatabaseConnection,
    a: comments::ActiveModel,
) -> StatusResult<comments::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_comments(
    db: &DatabaseConnection,
    a: comments::ActiveModel,
) -> StatusResult<comments::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_comments(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    comments::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
