//! The `content_model` repository (the reference's content_model_repo.go).

//! miscRepo — the data layer of the misc domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait, ConnectionTrait, DatabaseConnection, EntityTrait, QueryFilter};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{
    content_model_translations, content_models, field_definition_translations, field_definitions,
};

pub async fn content_models_by_id<C: ConnectionTrait>(
    db: &C,
    id: i64,
) -> StatusResult<content_models::Model> {
    content_models::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("content models"))
}
pub async fn insert_content_models<C: ConnectionTrait>(
    db: &C,
    a: content_models::ActiveModel,
) -> StatusResult<content_models::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_content_models<C: ConnectionTrait>(
    db: &C,
    a: content_models::ActiveModel,
) -> StatusResult<content_models::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
/// One model's field-definition ids (the replace/delete cascade head).
pub async fn content_model_field_ids<C: ConnectionTrait>(
    db: &C,
    model_id: i64,
) -> StatusResult<Vec<i64>> {
    let rows = field_definitions::Entity::find()
        .filter(field_definitions::Column::ContentModelId.eq(model_id))
        .all(db)
        .await
        .map_err(db_status)?;
    Ok(rows.into_iter().map(|r| r.id).collect())
}
pub async fn delete_field_definition_translations_of<C: ConnectionTrait>(
    db: &C,
    field_ids: &[i64],
) -> StatusResult<()> {
    use sea_orm::EntityTrait as _;
    if field_ids.is_empty() {
        return Ok(());
    }
    field_definition_translations::Entity::delete_many()
        .filter(field_definition_translations::Column::FieldDefinitionId.is_in(field_ids.to_vec()))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
pub async fn delete_field_definitions_of<C: ConnectionTrait>(
    db: &C,
    model_id: i64,
) -> StatusResult<()> {
    use sea_orm::EntityTrait as _;
    field_definitions::Entity::delete_many()
        .filter(field_definitions::Column::ContentModelId.eq(model_id))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
pub async fn insert_field_definitions<C: ConnectionTrait>(
    db: &C,
    a: field_definitions::ActiveModel,
) -> StatusResult<field_definitions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn insert_field_definition_translations<C: ConnectionTrait>(
    db: &C,
    a: field_definition_translations::ActiveModel,
) -> StatusResult<()> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)?;
    Ok(())
}
pub async fn field_definitions_of<C: ConnectionTrait>(
    db: &C,
    model_id: i64,
) -> StatusResult<Vec<field_definitions::Model>> {
    use sea_orm::QueryOrder as _;
    field_definitions::Entity::find()
        .filter(field_definitions::Column::ContentModelId.eq(model_id))
        .order_by_asc(field_definitions::Column::SortOrder)
        .order_by_asc(field_definitions::Column::Id)
        .all(db)
        .await
        .map_err(db_status)
}
pub async fn field_definition_translations_of<C: ConnectionTrait>(
    db: &C,
    field_id: i64,
) -> StatusResult<Vec<field_definition_translations::Model>> {
    use sea_orm::QueryOrder as _;
    field_definition_translations::Entity::find()
        .filter(field_definition_translations::Column::FieldDefinitionId.eq(field_id))
        .order_by_asc(field_definition_translations::Column::Id)
        .all(db)
        .await
        .map_err(db_status)
}
pub async fn delete_content_model_translations_of<C: ConnectionTrait>(
    db: &C,
    model_id: i64,
) -> StatusResult<()> {
    use sea_orm::EntityTrait as _;
    content_model_translations::Entity::delete_many()
        .filter(content_model_translations::Column::ContentModelId.eq(model_id))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
pub async fn insert_content_model_translations<C: ConnectionTrait>(
    db: &C,
    a: content_model_translations::ActiveModel,
) -> StatusResult<()> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)?;
    Ok(())
}
pub async fn delete_content_models(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    content_models::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
