//! dictRepo — the data layer of the dict domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{sys_dict_entries, sys_dict_types, sys_languages};

pub async fn languages_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_languages::Model> {
    sys_languages::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("languages"))
}

pub async fn insert_languages(
    db: &DatabaseConnection,
    a: sys_languages::ActiveModel,
) -> StatusResult<sys_languages::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_languages(
    db: &DatabaseConnection,
    a: sys_languages::ActiveModel,
) -> StatusResult<sys_languages::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_languages(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_languages::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn dict_types_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_dict_types::Model> {
    sys_dict_types::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("dict types"))
}

pub async fn insert_dict_types(
    db: &DatabaseConnection,
    a: sys_dict_types::ActiveModel,
) -> StatusResult<sys_dict_types::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_dict_types(
    db: &DatabaseConnection,
    a: sys_dict_types::ActiveModel,
) -> StatusResult<sys_dict_types::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_dict_types(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_dict_types::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn dict_entries_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_dict_entries::Model> {
    sys_dict_entries::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("dict entries"))
}

pub async fn insert_dict_entries(
    db: &DatabaseConnection,
    a: sys_dict_entries::ActiveModel,
) -> StatusResult<sys_dict_entries::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_dict_entries(
    db: &DatabaseConnection,
    a: sys_dict_entries::ActiveModel,
) -> StatusResult<sys_dict_entries::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_dict_entries(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_dict_entries::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
