//! identityRepo — the data layer of the identity domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{
    sys_role_permissions, sys_roles, sys_tenants, sys_user_credentials, sys_user_roles, sys_users,
};

pub async fn users_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_users::Model> {
    sys_users::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("users"))
}

pub async fn insert_users(
    db: &DatabaseConnection,
    a: sys_users::ActiveModel,
) -> StatusResult<sys_users::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_users(
    db: &DatabaseConnection,
    a: sys_users::ActiveModel,
) -> StatusResult<sys_users::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_users(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_users::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn roles_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_roles::Model> {
    sys_roles::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("roles"))
}

pub async fn insert_roles(
    db: &DatabaseConnection,
    a: sys_roles::ActiveModel,
) -> StatusResult<sys_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_roles(
    db: &DatabaseConnection,
    a: sys_roles::ActiveModel,
) -> StatusResult<sys_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_roles(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_roles::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn tenants_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_tenants::Model> {
    sys_tenants::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("tenants"))
}

pub async fn insert_tenants(
    db: &DatabaseConnection,
    a: sys_tenants::ActiveModel,
) -> StatusResult<sys_tenants::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_tenants(
    db: &DatabaseConnection,
    a: sys_tenants::ActiveModel,
) -> StatusResult<sys_tenants::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_tenants(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_tenants::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn user_credentials_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_user_credentials::Model> {
    sys_user_credentials::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("user credentials"))
}

pub async fn insert_user_credentials(
    db: &DatabaseConnection,
    a: sys_user_credentials::ActiveModel,
) -> StatusResult<sys_user_credentials::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_user_credentials(
    db: &DatabaseConnection,
    a: sys_user_credentials::ActiveModel,
) -> StatusResult<sys_user_credentials::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_user_credentials(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_user_credentials::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn user_roles_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_user_roles::Model> {
    sys_user_roles::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("user roles"))
}

pub async fn insert_user_roles(
    db: &DatabaseConnection,
    a: sys_user_roles::ActiveModel,
) -> StatusResult<sys_user_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_user_roles(
    db: &DatabaseConnection,
    a: sys_user_roles::ActiveModel,
) -> StatusResult<sys_user_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_user_roles(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_user_roles::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn role_permissions_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_role_permissions::Model> {
    sys_role_permissions::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("role permissions"))
}

pub async fn insert_role_permissions(
    db: &DatabaseConnection,
    a: sys_role_permissions::ActiveModel,
) -> StatusResult<sys_role_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_role_permissions(
    db: &DatabaseConnection,
    a: sys_role_permissions::ActiveModel,
) -> StatusResult<sys_role_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_role_permissions(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_role_permissions::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
