//! identityRepo — the data layer of the identity domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait as _, DatabaseConnection, EntityTrait, QueryFilter as _};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{
    sys_role_metadata, sys_role_permissions, sys_roles, sys_tenants, sys_user_credentials,
    sys_user_roles, sys_users,
};

pub async fn users_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_users::Model> {
    sys_users::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("users"))
}

pub async fn insert_users(
    db: &DatabaseConnection,
    a: sys_users::ActiveModel,
) -> StatusResult<sys_users::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_users(
    db: &DatabaseConnection,
    a: sys_users::ActiveModel,
) -> StatusResult<sys_users::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_users(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_users::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn roles_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_roles::Model> {
    sys_roles::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("roles"))
}

pub async fn insert_roles(
    db: &DatabaseConnection,
    a: sys_roles::ActiveModel,
) -> StatusResult<sys_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_roles(
    db: &DatabaseConnection,
    a: sys_roles::ActiveModel,
) -> StatusResult<sys_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_roles(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_roles::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn tenants_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_tenants::Model> {
    sys_tenants::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("tenants"))
}

pub async fn insert_tenants(
    db: &DatabaseConnection,
    a: sys_tenants::ActiveModel,
) -> StatusResult<sys_tenants::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_tenants(
    db: &DatabaseConnection,
    a: sys_tenants::ActiveModel,
) -> StatusResult<sys_tenants::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_tenants(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_tenants::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn user_credentials_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_user_credentials::Model> {
    sys_user_credentials::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("user credentials"))
}

pub async fn insert_user_credentials(
    db: &DatabaseConnection,
    a: sys_user_credentials::ActiveModel,
) -> StatusResult<sys_user_credentials::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_user_credentials(
    db: &DatabaseConnection,
    a: sys_user_credentials::ActiveModel,
) -> StatusResult<sys_user_credentials::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_user_credentials(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_user_credentials::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn user_roles_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_user_roles::Model> {
    sys_user_roles::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("user roles"))
}

pub async fn insert_user_roles(
    db: &DatabaseConnection,
    a: sys_user_roles::ActiveModel,
) -> StatusResult<sys_user_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_user_roles(
    db: &DatabaseConnection,
    a: sys_user_roles::ActiveModel,
) -> StatusResult<sys_user_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_user_roles(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_user_roles::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn role_permissions_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_role_permissions::Model> {
    sys_role_permissions::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("role permissions"))
}

pub async fn insert_role_permissions(
    db: &DatabaseConnection,
    a: sys_role_permissions::ActiveModel,
) -> StatusResult<sys_role_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_role_permissions(
    db: &DatabaseConnection,
    a: sys_role_permissions::ActiveModel,
) -> StatusResult<sys_role_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_role_permissions(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_role_permissions::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

// ── domain-specific queries ─────────────────────────────────────────
// (the role/user-role read helpers behind RoleService — the port of the
// reference's role_repo / user_role_repo query faces)

/// Role codes by role ids (ListRoleCodesByRoleIds); empty in, empty out.
pub async fn role_codes_by_ids(
    db: &DatabaseConnection,
    role_ids: &[i64],
) -> StatusResult<Vec<String>> {
    if role_ids.is_empty() {
        return Ok(Vec::new());
    }
    let rows = sys_roles::Entity::find()
        .filter(sys_roles::Column::Id.is_in(role_ids.to_vec()))
        .all(db)
        .await
        .map_err(db_status)?;
    Ok(rows.into_iter().filter_map(|r| r.code).collect())
}

/// Role ids by role codes inside one tenant (ListRoleIDsByRoleCodes).
/// `role.code` is unique only per (tenant_id, code), so the caller
/// enforces the tenant scope the reference requires (tid > 0).
pub async fn role_ids_by_codes(
    db: &DatabaseConnection,
    codes: &[String],
    tenant_id: i64,
) -> StatusResult<Vec<i64>> {
    if codes.is_empty() {
        return Ok(Vec::new());
    }
    let rows = sys_roles::Entity::find()
        .filter(
            sea_orm::Condition::all()
                .add(sys_roles::Column::Code.is_in(codes.to_vec()))
                .add(sys_roles::Column::TenantId.eq(tenant_id)),
        )
        .all(db)
        .await
        .map_err(db_status)?;
    Ok(rows.into_iter().map(|r| r.id).collect())
}

/// Permission ids bound to the given role ids (ListPermissionIDsByRoleIDs).
pub async fn permission_ids_by_role_ids(
    db: &DatabaseConnection,
    role_ids: &[i64],
) -> StatusResult<Vec<i64>> {
    if role_ids.is_empty() {
        return Ok(Vec::new());
    }
    let rows = sys_role_permissions::Entity::find()
        .filter(sys_role_permissions::Column::RoleId.is_in(role_ids.to_vec()))
        .all(db)
        .await
        .map_err(db_status)?;
    Ok(rows.into_iter().map(|r| r.permission_id).collect())
}

/// The user's role ids (ListRoleIDs). `include_expired` keeps bindings
/// past their `end_at` — the reference filters them unless asked to.
pub async fn user_role_ids(
    db: &DatabaseConnection,
    user_id: i64,
    include_expired: bool,
) -> StatusResult<Vec<i64>> {
    if user_id == 0 {
        return Ok(Vec::new());
    }
    Ok(user_roles_by_user_id(db, user_id, include_expired)
        .await?
        .into_iter()
        .map(|r| r.role_id)
        .collect())
}

/// The user's role binding rows (ListByUserID), newest-binding order is
/// the table order; expired rows dropped unless `include_expired`.
pub async fn user_roles_by_user_id(
    db: &DatabaseConnection,
    user_id: i64,
    include_expired: bool,
) -> StatusResult<Vec<sys_user_roles::Model>> {
    if user_id == 0 {
        return Ok(Vec::new());
    }
    let mut query =
        sys_user_roles::Entity::find().filter(sys_user_roles::Column::UserId.eq(user_id));
    if !include_expired {
        query = query.filter(
            sea_orm::Condition::any()
                .add(sys_user_roles::Column::EndAt.is_null())
                .add(sys_user_roles::Column::EndAt.gt(store::now())),
        );
    }
    query.all(db).await.map_err(db_status)
}

/// The role-metadata row of one role (roleMetadataRepo.Get); `None`
/// when the role carries no metadata row.
pub async fn role_metadata_by_role_id(
    db: &DatabaseConnection,
    role_id: i64,
) -> StatusResult<Option<sys_role_metadata::Model>> {
    sys_role_metadata::Entity::find()
        .filter(sys_role_metadata::Column::RoleId.eq(role_id))
        .one(db)
        .await
        .map_err(db_status)
}
