//! The `interaction` repository (the reference's interaction_repo.go).

//! socialRepo — the data layer of the social domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{
    ActiveModelTrait, ColumnTrait, ConnectionTrait, DatabaseConnection, EntityTrait,
    PaginatorTrait, QueryFilter, Set,
};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{comment_likes, interaction_counters, post_likes, post_watches};

















// ── Interaction purge/recount helpers (the reference's
//    adjustCounterRow / purge / reset tail of interaction_repo.go) ────

pub async fn interaction_counters_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<interaction_counters::Model> {
    interaction_counters::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("interaction counters"))
}
pub async fn insert_interaction_counters(
    db: &DatabaseConnection,
    a: interaction_counters::ActiveModel,
) -> StatusResult<interaction_counters::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_interaction_counters(
    db: &DatabaseConnection,
    a: interaction_counters::ActiveModel,
) -> StatusResult<interaction_counters::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_interaction_counters(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    interaction_counters::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
pub async fn post_likes_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<post_likes::Model> {
    post_likes::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("post likes"))
}
pub async fn insert_post_likes(
    db: &DatabaseConnection,
    a: post_likes::ActiveModel,
) -> StatusResult<post_likes::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_post_likes(
    db: &DatabaseConnection,
    a: post_likes::ActiveModel,
) -> StatusResult<post_likes::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_post_likes(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    post_likes::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
pub async fn post_watches_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<post_watches::Model> {
    post_watches::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("post watches"))
}
pub async fn insert_post_watches(
    db: &DatabaseConnection,
    a: post_watches::ActiveModel,
) -> StatusResult<post_watches::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_post_watches(
    db: &DatabaseConnection,
    a: post_watches::ActiveModel,
) -> StatusResult<post_watches::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_post_watches(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    post_watches::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// The current counter value of one (target, metric) row; the missing
/// row reads 0. Like the service-face counters, the lookup carries no
/// tenant filter (the interaction domain's rows are stamped but not
/// tenant-scoped).
pub async fn counter_of<C: ConnectionTrait>(
    db: &C,
    target_type: i16,
    target_id: i64,
    metric: i16,
) -> StatusResult<i64> {
    Ok(counter_row(db, target_type, target_id, metric)
        .await?
        .and_then(|r| r.count)
        .unwrap_or(0))
}
/// The counter upsert/decrement (the reference's adjustCounterRow): the
/// missing row is created only for a positive delta; a row pushed to 0
/// or below is deleted.
pub async fn adjust_counter<C: ConnectionTrait>(
    db: &C,
    tenant_id: i64,
    target_type: i16,
    target_id: i64,
    metric: i16,
    delta: i64,
) -> StatusResult<()> {
    let Some(row) = counter_row(db, target_type, target_id, metric).await? else {
        if delta <= 0 {
            // No row to decrement — the idempotent no-op.
            return Ok(());
        }
        interaction_counters::ActiveModel {
            tenant_id: Set(Some(tenant_id)),
            target_type: Set(Some(target_type)),
            target_id: Set(Some(target_id)),
            metric: Set(Some(metric)),
            count: Set(Some(delta)),
            created_at: Set(Some(store::now())),
            ..Default::default()
        }
        .insert(db)
        .await
        .map_err(db_status)?;
        return Ok(());
    };
    let next = row.count.unwrap_or(0) + delta;
    if next <= 0 {
        // The zeroed count drops the row (the reference's归0删行 branch).
        interaction_counters::Entity::delete_by_id(row.id)
            .exec(db)
            .await
            .map_err(db_status)?;
        return Ok(());
    }
    let mut a: interaction_counters::ActiveModel = row.into();
    a.count = Set(Some(next));
    a.update(db).await.map_err(db_status)?;
    Ok(())
}
async fn counter_row<C: ConnectionTrait>(
    db: &C,
    target_type: i16,
    target_id: i64,
    metric: i16,
) -> StatusResult<Option<interaction_counters::Model>> {
    interaction_counters::Entity::find()
        .filter(
            sea_orm::Condition::all()
                .add(interaction_counters::Column::TargetType.eq(target_type))
                .add(interaction_counters::Column::TargetId.eq(target_id))
                .add(interaction_counters::Column::Metric.eq(metric)),
        )
        .one(db)
        .await
        .map_err(db_status)
}
/// The ledger truth for one (target, metric) — the recount source of
/// ResetCounter. LIKE off the post/comment like ledgers, WATCH off the
/// post watches.
pub async fn count_ledger<C: ConnectionTrait>(
    db: &C,
    metric: i16,
    target_type: i16,
    target_id: i64,
) -> StatusResult<u64> {
    match (metric, target_type) {
        (1, 2) => comment_likes_target_count(db, target_id).await,
        (2, _) => post_watches_target_count(db, target_id).await,
        _ => post_likes_target_count(db, target_id).await,
    }
}
pub async fn post_likes_target_count<C: ConnectionTrait>(
    db: &C,
    post_id: i64,
) -> StatusResult<u64> {
    post_likes::Entity::find()
        .filter(post_likes::Column::PostId.eq(post_id))
        .count(db)
        .await
        .map_err(db_status)
}
pub async fn comment_likes_target_count<C: ConnectionTrait>(
    db: &C,
    comment_id: i64,
) -> StatusResult<u64> {
    comment_likes::Entity::find()
        .filter(comment_likes::Column::CommentId.eq(comment_id))
        .count(db)
        .await
        .map_err(db_status)
}
pub async fn post_watches_target_count<C: ConnectionTrait>(
    db: &C,
    post_id: i64,
) -> StatusResult<u64> {
    post_watches::Entity::find()
        .filter(post_watches::Column::PostId.eq(post_id))
        .count(db)
        .await
        .map_err(db_status)
}
/// The per-target ledger wipes of PurgeTargetInteractions, returning the
/// rows removed.
pub async fn delete_post_likes_of_post<C: ConnectionTrait>(
    db: &C,
    post_id: i64,
) -> StatusResult<u64> {
    let res = post_likes::Entity::delete_many()
        .filter(post_likes::Column::PostId.eq(post_id))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(res.rows_affected)
}
pub async fn delete_comment_likes_of_comment<C: ConnectionTrait>(
    db: &C,
    comment_id: i64,
) -> StatusResult<u64> {
    let res = comment_likes::Entity::delete_many()
        .filter(comment_likes::Column::CommentId.eq(comment_id))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(res.rows_affected)
}
pub async fn delete_post_watches_of_post<C: ConnectionTrait>(
    db: &C,
    post_id: i64,
) -> StatusResult<u64> {
    let res = post_watches::Entity::delete_many()
        .filter(post_watches::Column::PostId.eq(post_id))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(res.rows_affected)
}
/// The target ids of a user's ledger rows (the PurgeUserInteractions
/// scan; each id rolls its counter back one step before the wipe).
pub async fn post_like_targets_of_user<C: ConnectionTrait>(
    db: &C,
    user_id: i64,
) -> StatusResult<Vec<i64>> {
    Ok(post_likes::Entity::find()
        .filter(post_likes::Column::UserId.eq(user_id))
        .all(db)
        .await
        .map_err(db_status)?
        .into_iter()
        .filter_map(|r| r.post_id)
        .collect())
}
pub async fn comment_like_targets_of_user<C: ConnectionTrait>(
    db: &C,
    user_id: i64,
) -> StatusResult<Vec<i64>> {
    Ok(comment_likes::Entity::find()
        .filter(comment_likes::Column::UserId.eq(user_id))
        .all(db)
        .await
        .map_err(db_status)?
        .into_iter()
        .filter_map(|r| r.comment_id)
        .collect())
}
pub async fn post_watch_targets_of_user<C: ConnectionTrait>(
    db: &C,
    user_id: i64,
) -> StatusResult<Vec<i64>> {
    Ok(post_watches::Entity::find()
        .filter(post_watches::Column::UserId.eq(user_id))
        .all(db)
        .await
        .map_err(db_status)?
        .into_iter()
        .filter_map(|r| r.post_id)
        .collect())
}
