//! The `internal_message` repository (the reference's internal_message_repo.go).

//! messagingRepo — the data layer of the messaging domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::internal_messages;

// ── domain-specific queries ──────────────────────────────────────────

pub async fn internal_messages_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<internal_messages::Model> {
    internal_messages::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("internal messages"))
}
pub async fn insert_internal_messages(
    db: &DatabaseConnection,
    a: internal_messages::ActiveModel,
) -> StatusResult<internal_messages::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_internal_messages(
    db: &DatabaseConnection,
    a: internal_messages::ActiveModel,
) -> StatusResult<internal_messages::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_internal_messages(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    internal_messages::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
