//! The `internal_message_category` repository (the reference's internal_message_category_repo.go).

//! miscRepo — the data layer of the misc domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait, ConnectionTrait, DatabaseConnection, EntityTrait, QueryFilter};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::internal_message_categories;

pub async fn internal_message_categories_by_id<C: ConnectionTrait>(
    db: &C,
    id: i64,
) -> StatusResult<internal_message_categories::Model> {
    internal_message_categories::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("internal message categories"))
}
pub async fn insert_internal_message_categories<C: ConnectionTrait>(
    db: &C,
    a: internal_message_categories::ActiveModel,
) -> StatusResult<internal_message_categories::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_internal_message_categories<C: ConnectionTrait>(
    db: &C,
    a: internal_message_categories::ActiveModel,
) -> StatusResult<internal_message_categories::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_internal_message_categories(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<()> {
    internal_message_categories::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// All descendant ids of one message category (level-by-level walk),
/// root excluded.
pub async fn internal_message_category_descendant_ids(
    db: &DatabaseConnection,
    root: i64,
) -> StatusResult<Vec<i64>> {
    let mut ids = Vec::new();
    let mut frontier = vec![root];
    while !frontier.is_empty() {
        let rows = internal_message_categories::Entity::find()
            .filter(internal_message_categories::Column::ParentId.is_in(frontier.clone()))
            .all(db)
            .await
            .map_err(db_status)?;
        frontier = rows
            .into_iter()
            .map(|r| r.id)
            .filter(|id| !ids.contains(id) && *id != root)
            .collect();
        ids.extend(frontier.iter().copied());
    }
    Ok(ids)
}
