//! The `login_policy` repository (the reference's login_policy_repo.go).

//! miscRepo — the data layer of the misc domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_login_policies;

pub async fn login_policies_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_login_policies::Model> {
    sys_login_policies::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("login policies"))
}
pub async fn insert_login_policies(
    db: &DatabaseConnection,
    a: sys_login_policies::ActiveModel,
) -> StatusResult<sys_login_policies::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_login_policies(
    db: &DatabaseConnection,
    a: sys_login_policies::ActiveModel,
) -> StatusResult<sys_login_policies::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_login_policies(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_login_policies::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
