//! The `media_asset` repository (the reference's media_asset_repo.go).

//! miscRepo — the data layer of the misc domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::media_assets;

pub async fn media_assets_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<media_assets::Model> {
    media_assets::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("media assets"))
}
pub async fn insert_media_assets(
    db: &DatabaseConnection,
    a: media_assets::ActiveModel,
) -> StatusResult<media_assets::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_media_assets(
    db: &DatabaseConnection,
    a: media_assets::ActiveModel,
) -> StatusResult<media_assets::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_media_assets(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    media_assets::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
