//! The `menu` repository (the reference's menu_repo.go).

//! permissionRepo — the data layer of the permission domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_menus;

// ── domain-specific queries ─────────────────────────────────────────

// ── the sync face's rebuild pipeline ────────────────────────────────

pub async fn menus_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_menus::Model> {
    sys_menus::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("menus"))
}
pub async fn insert_menus(
    db: &DatabaseConnection,
    a: sys_menus::ActiveModel,
) -> StatusResult<sys_menus::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_menus(
    db: &DatabaseConnection,
    a: sys_menus::ActiveModel,
) -> StatusResult<sys_menus::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_menus(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_menus::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// The enabled menus, newest id first (the sync scan order).
pub async fn menus_enabled_desc(db: &DatabaseConnection) -> StatusResult<Vec<sys_menus::Model>> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _, QueryOrder as _};
    sys_menus::Entity::find()
        .filter(sys_menus::Column::Status.eq("ON"))
        .order_by_desc(sys_menus::Column::Id)
        .all(db)
        .await
        .map_err(db_status)
}
