//! messagingRepo — the data layer of the messaging domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use chrono::{DateTime, FixedOffset};
use sea_orm::{ColumnTrait, DatabaseConnection, EntityTrait, QueryFilter, Set};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{internal_message_recipients, internal_messages, sys_tasks};

pub async fn internal_messages_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<internal_messages::Model> {
    internal_messages::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("internal messages"))
}

pub async fn insert_internal_messages(
    db: &DatabaseConnection,
    a: internal_messages::ActiveModel,
) -> StatusResult<internal_messages::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_internal_messages(
    db: &DatabaseConnection,
    a: internal_messages::ActiveModel,
) -> StatusResult<internal_messages::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_internal_messages(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    internal_messages::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn internal_message_recipients_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<internal_message_recipients::Model> {
    internal_message_recipients::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("internal message recipients"))
}

pub async fn insert_internal_message_recipients(
    db: &DatabaseConnection,
    a: internal_message_recipients::ActiveModel,
) -> StatusResult<internal_message_recipients::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_internal_message_recipients(
    db: &DatabaseConnection,
    a: internal_message_recipients::ActiveModel,
) -> StatusResult<internal_message_recipients::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_internal_message_recipients(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<()> {
    internal_message_recipients::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn tasks_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_tasks::Model> {
    sys_tasks::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("tasks"))
}

pub async fn insert_tasks(
    db: &DatabaseConnection,
    a: sys_tasks::ActiveModel,
) -> StatusResult<sys_tasks::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_tasks(
    db: &DatabaseConnection,
    a: sys_tasks::ActiveModel,
) -> StatusResult<sys_tasks::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_tasks(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_tasks::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

// ── domain-specific queries ──────────────────────────────────────────

/// The reference's MarkNotificationsStatus bulk update: the caller's own
/// rows only, never ones already in the target state; the timestamp
/// column follows the target state (READ → read_at, RECEIVED →
/// received_at), everything else just flips status + updated_at.
pub async fn mark_notifications_status(
    db: &DatabaseConnection,
    recipient_ids: Vec<i64>,
    recipient_user_id: i64,
    new_status: &str,
    now: DateTime<FixedOffset>,
) -> StatusResult<()> {
    let mut patch = internal_message_recipients::ActiveModel {
        status: Set(Some(new_status.to_string())),
        updated_at: Set(Some(now)),
        ..Default::default()
    };
    match new_status {
        "READ" => patch.read_at = Set(Some(now)),
        "RECEIVED" => patch.received_at = Set(Some(now)),
        _ => {}
    }
    internal_message_recipients::Entity::update_many()
        .set(patch)
        .filter(internal_message_recipients::Column::Id.is_in(recipient_ids))
        .filter(internal_message_recipients::Column::RecipientUserId.eq(recipient_user_id))
        .filter(internal_message_recipients::Column::Status.ne(new_status))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

/// The (tenant_id, type_name) lookup of the reference's Get-by-TypeName
/// (unique within a tenant).
pub async fn task_by_type_name(
    db: &DatabaseConnection,
    type_name: &str,
    tenant_id: i64,
) -> StatusResult<Option<sys_tasks::Model>> {
    sys_tasks::Entity::find()
        .filter(sys_tasks::Column::TypeName.eq(type_name))
        .filter(sys_tasks::Column::TenantId.eq(tenant_id))
        .one(db)
        .await
        .map_err(db_status)
}

/// The reference's tenant-scoped bulk delete of a task (a silent no-op on
/// missing rows, like the reference's `Delete().Where().Exec`).
pub async fn delete_task_scoped(
    db: &DatabaseConnection,
    id: i64,
    tenant_id: Option<i64>,
) -> StatusResult<()> {
    let mut del = sys_tasks::Entity::delete_many().filter(sys_tasks::Column::Id.eq(id));
    if let Some(tid) = tenant_id {
        del = del.filter(sys_tasks::Column::TenantId.eq(tid));
    }
    del.exec(db).await.map_err(db_status)?;
    Ok(())
}
