//! messagingRepo — the data layer of the messaging domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{internal_message_recipients, internal_messages, sys_tasks};

pub async fn internal_messages_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<internal_messages::Model> {
    internal_messages::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("internal messages"))
}

pub async fn insert_internal_messages(
    db: &DatabaseConnection,
    a: internal_messages::ActiveModel,
) -> StatusResult<internal_messages::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_internal_messages(
    db: &DatabaseConnection,
    a: internal_messages::ActiveModel,
) -> StatusResult<internal_messages::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_internal_messages(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    internal_messages::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn internal_message_recipients_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<internal_message_recipients::Model> {
    internal_message_recipients::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("internal message recipients"))
}

pub async fn insert_internal_message_recipients(
    db: &DatabaseConnection,
    a: internal_message_recipients::ActiveModel,
) -> StatusResult<internal_message_recipients::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_internal_message_recipients(
    db: &DatabaseConnection,
    a: internal_message_recipients::ActiveModel,
) -> StatusResult<internal_message_recipients::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_internal_message_recipients(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<()> {
    internal_message_recipients::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn tasks_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_tasks::Model> {
    sys_tasks::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("tasks"))
}

pub async fn insert_tasks(
    db: &DatabaseConnection,
    a: sys_tasks::ActiveModel,
) -> StatusResult<sys_tasks::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_tasks(
    db: &DatabaseConnection,
    a: sys_tasks::ActiveModel,
) -> StatusResult<sys_tasks::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_tasks(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_tasks::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
