//! miscRepo — the data layer of the misc domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait, ConnectionTrait, DatabaseConnection, EntityTrait, QueryFilter};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{
    content_model_translations, content_models, field_definition_translations, field_definitions,
    internal_message_categories, media_assets, sys_login_policies, sys_org_units, sys_positions,
};

/// The org-unit faces run inside a transaction (the reference wraps
/// the create + tree-path backfill in one), so they take the generic
/// connection trait.
pub async fn org_units_by_id<C: ConnectionTrait>(
    db: &C,
    id: i64,
) -> StatusResult<sys_org_units::Model> {
    sys_org_units::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("org units"))
}

pub async fn insert_org_units<C: ConnectionTrait>(
    db: &C,
    a: sys_org_units::ActiveModel,
) -> StatusResult<sys_org_units::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_org_units<C: ConnectionTrait>(
    db: &C,
    a: sys_org_units::ActiveModel,
) -> StatusResult<sys_org_units::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_org_units(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_org_units::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

/// All descendant ids of one org unit (level-by-level walk — the
/// recursive-CTE equivalent), root excluded.
pub async fn org_unit_descendant_ids(db: &DatabaseConnection, root: i64) -> StatusResult<Vec<i64>> {
    let mut ids = Vec::new();
    let mut frontier = vec![root];
    while !frontier.is_empty() {
        let rows = sys_org_units::Entity::find()
            .filter(sys_org_units::Column::ParentId.is_in(frontier.clone()))
            .all(db)
            .await
            .map_err(db_status)?;
        frontier = rows
            .into_iter()
            .map(|r| r.id)
            .filter(|id| !ids.contains(id) && *id != root)
            .collect();
        ids.extend(frontier.iter().copied());
    }
    Ok(ids)
}

pub async fn positions_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_positions::Model> {
    sys_positions::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("positions"))
}

pub async fn insert_positions(
    db: &DatabaseConnection,
    a: sys_positions::ActiveModel,
) -> StatusResult<sys_positions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_positions(
    db: &DatabaseConnection,
    a: sys_positions::ActiveModel,
) -> StatusResult<sys_positions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_positions(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_positions::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn login_policies_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_login_policies::Model> {
    sys_login_policies::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("login policies"))
}

pub async fn insert_login_policies(
    db: &DatabaseConnection,
    a: sys_login_policies::ActiveModel,
) -> StatusResult<sys_login_policies::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_login_policies(
    db: &DatabaseConnection,
    a: sys_login_policies::ActiveModel,
) -> StatusResult<sys_login_policies::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_login_policies(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_login_policies::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn content_models_by_id<C: ConnectionTrait>(
    db: &C,
    id: i64,
) -> StatusResult<content_models::Model> {
    content_models::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("content models"))
}

pub async fn insert_content_models<C: ConnectionTrait>(
    db: &C,
    a: content_models::ActiveModel,
) -> StatusResult<content_models::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_content_models<C: ConnectionTrait>(
    db: &C,
    a: content_models::ActiveModel,
) -> StatusResult<content_models::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

/// One model's field-definition ids (the replace/delete cascade head).
pub async fn content_model_field_ids<C: ConnectionTrait>(
    db: &C,
    model_id: i64,
) -> StatusResult<Vec<i64>> {
    let rows = field_definitions::Entity::find()
        .filter(field_definitions::Column::ContentModelId.eq(model_id))
        .all(db)
        .await
        .map_err(db_status)?;
    Ok(rows.into_iter().map(|r| r.id).collect())
}

pub async fn delete_field_definition_translations_of<C: ConnectionTrait>(
    db: &C,
    field_ids: &[i64],
) -> StatusResult<()> {
    use sea_orm::EntityTrait as _;
    if field_ids.is_empty() {
        return Ok(());
    }
    field_definition_translations::Entity::delete_many()
        .filter(field_definition_translations::Column::FieldDefinitionId.is_in(field_ids.to_vec()))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn delete_field_definitions_of<C: ConnectionTrait>(
    db: &C,
    model_id: i64,
) -> StatusResult<()> {
    use sea_orm::EntityTrait as _;
    field_definitions::Entity::delete_many()
        .filter(field_definitions::Column::ContentModelId.eq(model_id))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn insert_field_definitions<C: ConnectionTrait>(
    db: &C,
    a: field_definitions::ActiveModel,
) -> StatusResult<field_definitions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn insert_field_definition_translations<C: ConnectionTrait>(
    db: &C,
    a: field_definition_translations::ActiveModel,
) -> StatusResult<()> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)?;
    Ok(())
}

pub async fn field_definitions_of<C: ConnectionTrait>(
    db: &C,
    model_id: i64,
) -> StatusResult<Vec<field_definitions::Model>> {
    use sea_orm::QueryOrder as _;
    field_definitions::Entity::find()
        .filter(field_definitions::Column::ContentModelId.eq(model_id))
        .order_by_asc(field_definitions::Column::SortOrder)
        .order_by_asc(field_definitions::Column::Id)
        .all(db)
        .await
        .map_err(db_status)
}

pub async fn field_definition_translations_of<C: ConnectionTrait>(
    db: &C,
    field_id: i64,
) -> StatusResult<Vec<field_definition_translations::Model>> {
    use sea_orm::QueryOrder as _;
    field_definition_translations::Entity::find()
        .filter(field_definition_translations::Column::FieldDefinitionId.eq(field_id))
        .order_by_asc(field_definition_translations::Column::Id)
        .all(db)
        .await
        .map_err(db_status)
}

pub async fn delete_content_model_translations_of<C: ConnectionTrait>(
    db: &C,
    model_id: i64,
) -> StatusResult<()> {
    use sea_orm::EntityTrait as _;
    content_model_translations::Entity::delete_many()
        .filter(content_model_translations::Column::ContentModelId.eq(model_id))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn insert_content_model_translations<C: ConnectionTrait>(
    db: &C,
    a: content_model_translations::ActiveModel,
) -> StatusResult<()> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)?;
    Ok(())
}

pub async fn internal_message_categories_by_id<C: ConnectionTrait>(
    db: &C,
    id: i64,
) -> StatusResult<internal_message_categories::Model> {
    internal_message_categories::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("internal message categories"))
}

pub async fn insert_internal_message_categories<C: ConnectionTrait>(
    db: &C,
    a: internal_message_categories::ActiveModel,
) -> StatusResult<internal_message_categories::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_internal_message_categories<C: ConnectionTrait>(
    db: &C,
    a: internal_message_categories::ActiveModel,
) -> StatusResult<internal_message_categories::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_internal_message_categories(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<()> {
    internal_message_categories::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

/// All descendant ids of one message category (level-by-level walk),
/// root excluded.
pub async fn internal_message_category_descendant_ids(
    db: &DatabaseConnection,
    root: i64,
) -> StatusResult<Vec<i64>> {
    let mut ids = Vec::new();
    let mut frontier = vec![root];
    while !frontier.is_empty() {
        let rows = internal_message_categories::Entity::find()
            .filter(internal_message_categories::Column::ParentId.is_in(frontier.clone()))
            .all(db)
            .await
            .map_err(db_status)?;
        frontier = rows
            .into_iter()
            .map(|r| r.id)
            .filter(|id| !ids.contains(id) && *id != root)
            .collect();
        ids.extend(frontier.iter().copied());
    }
    Ok(ids)
}

pub async fn delete_content_models(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    content_models::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn media_assets_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<media_assets::Model> {
    media_assets::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("media assets"))
}

pub async fn insert_media_assets(
    db: &DatabaseConnection,
    a: media_assets::ActiveModel,
) -> StatusResult<media_assets::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_media_assets(
    db: &DatabaseConnection,
    a: media_assets::ActiveModel,
) -> StatusResult<media_assets::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_media_assets(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    media_assets::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
