//! miscRepo — the data layer of the misc domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{
    content_models, media_assets, sys_login_policies, sys_org_units, sys_positions,
};

pub async fn org_units_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_org_units::Model> {
    sys_org_units::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("org units"))
}

pub async fn insert_org_units(
    db: &DatabaseConnection,
    a: sys_org_units::ActiveModel,
) -> StatusResult<sys_org_units::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_org_units(
    db: &DatabaseConnection,
    a: sys_org_units::ActiveModel,
) -> StatusResult<sys_org_units::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_org_units(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_org_units::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn positions_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_positions::Model> {
    sys_positions::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("positions"))
}

pub async fn insert_positions(
    db: &DatabaseConnection,
    a: sys_positions::ActiveModel,
) -> StatusResult<sys_positions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_positions(
    db: &DatabaseConnection,
    a: sys_positions::ActiveModel,
) -> StatusResult<sys_positions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_positions(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_positions::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn login_policies_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_login_policies::Model> {
    sys_login_policies::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("login policies"))
}

pub async fn insert_login_policies(
    db: &DatabaseConnection,
    a: sys_login_policies::ActiveModel,
) -> StatusResult<sys_login_policies::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_login_policies(
    db: &DatabaseConnection,
    a: sys_login_policies::ActiveModel,
) -> StatusResult<sys_login_policies::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_login_policies(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_login_policies::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn content_models_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<content_models::Model> {
    content_models::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("content models"))
}

pub async fn insert_content_models(
    db: &DatabaseConnection,
    a: content_models::ActiveModel,
) -> StatusResult<content_models::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_content_models(
    db: &DatabaseConnection,
    a: content_models::ActiveModel,
) -> StatusResult<content_models::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_content_models(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    content_models::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn media_assets_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<media_assets::Model> {
    media_assets::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("media assets"))
}

pub async fn insert_media_assets(
    db: &DatabaseConnection,
    a: media_assets::ActiveModel,
) -> StatusResult<media_assets::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_media_assets(
    db: &DatabaseConnection,
    a: media_assets::ActiveModel,
) -> StatusResult<media_assets::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_media_assets(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    media_assets::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
