//! The `navigation_item` repository (the reference's navigation_item_repo.go).

//! siteRepo — the data layer of the site domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::navigation_items;

pub async fn navigation_items_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<navigation_items::Model> {
    navigation_items::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("navigation items"))
}
pub async fn insert_navigation_items(
    db: &DatabaseConnection,
    a: navigation_items::ActiveModel,
) -> StatusResult<navigation_items::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_navigation_items(
    db: &DatabaseConnection,
    a: navigation_items::ActiveModel,
) -> StatusResult<navigation_items::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_navigation_items(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    navigation_items::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
