//! The `org_unit` repository (the reference's org_unit_repo.go).

//! miscRepo — the data layer of the misc domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait, ConnectionTrait, DatabaseConnection, EntityTrait, QueryFilter};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_org_units;

/// The org-unit faces run inside a transaction (the reference wraps
/// the create + tree-path backfill in one), so they take the generic
/// connection trait.
pub async fn org_units_by_id<C: ConnectionTrait>(
    db: &C,
    id: i64,
) -> StatusResult<sys_org_units::Model> {
    sys_org_units::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("org units"))
}
pub async fn insert_org_units<C: ConnectionTrait>(
    db: &C,
    a: sys_org_units::ActiveModel,
) -> StatusResult<sys_org_units::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_org_units<C: ConnectionTrait>(
    db: &C,
    a: sys_org_units::ActiveModel,
) -> StatusResult<sys_org_units::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_org_units(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_org_units::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// All descendant ids of one org unit (level-by-level walk — the
/// recursive-CTE equivalent), root excluded.
pub async fn org_unit_descendant_ids(db: &DatabaseConnection, root: i64) -> StatusResult<Vec<i64>> {
    let mut ids = Vec::new();
    let mut frontier = vec![root];
    while !frontier.is_empty() {
        let rows = sys_org_units::Entity::find()
            .filter(sys_org_units::Column::ParentId.is_in(frontier.clone()))
            .all(db)
            .await
            .map_err(db_status)?;
        frontier = rows
            .into_iter()
            .map(|r| r.id)
            .filter(|id| !ids.contains(id) && *id != root)
            .collect();
        ids.extend(frontier.iter().copied());
    }
    Ok(ids)
}
