//! permissionRepo — the data layer of the permission domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait, Set};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{
    sys_apis, sys_menus, sys_permission_apis, sys_permission_groups, sys_permission_menus,
    sys_permissions,
};

pub async fn menus_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_menus::Model> {
    sys_menus::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("menus"))
}

pub async fn insert_menus(
    db: &DatabaseConnection,
    a: sys_menus::ActiveModel,
) -> StatusResult<sys_menus::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_menus(
    db: &DatabaseConnection,
    a: sys_menus::ActiveModel,
) -> StatusResult<sys_menus::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_menus(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_menus::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn apis_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_apis::Model> {
    sys_apis::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("apis"))
}

pub async fn insert_apis(
    db: &DatabaseConnection,
    a: sys_apis::ActiveModel,
) -> StatusResult<sys_apis::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_apis(
    db: &DatabaseConnection,
    a: sys_apis::ActiveModel,
) -> StatusResult<sys_apis::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_apis(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_apis::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn permission_groups_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_permission_groups::Model> {
    sys_permission_groups::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("permission groups"))
}

pub async fn insert_permission_groups(
    db: &DatabaseConnection,
    a: sys_permission_groups::ActiveModel,
) -> StatusResult<sys_permission_groups::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_permission_groups(
    db: &DatabaseConnection,
    a: sys_permission_groups::ActiveModel,
) -> StatusResult<sys_permission_groups::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_permission_groups(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_permission_groups::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn permissions_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_permissions::Model> {
    sys_permissions::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("permissions"))
}

pub async fn insert_permissions(
    db: &DatabaseConnection,
    a: sys_permissions::ActiveModel,
) -> StatusResult<sys_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_permissions(
    db: &DatabaseConnection,
    a: sys_permissions::ActiveModel,
) -> StatusResult<sys_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_permissions(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_permissions::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

// ── domain-specific queries ─────────────────────────────────────────

/// The api row registered for one operation id (the sync face's
/// upsert lookup).
pub async fn apis_by_operation(
    db: &DatabaseConnection,
    operation: &str,
) -> StatusResult<Option<sys_apis::Model>> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _};
    sys_apis::Entity::find()
        .filter(sys_apis::Column::Operation.eq(operation))
        .one(db)
        .await
        .map_err(db_status)
}

// ── the sync face's rebuild pipeline ────────────────────────────────

/// The enabled menus, newest id first (the sync scan order).
pub async fn menus_enabled_desc(db: &DatabaseConnection) -> StatusResult<Vec<sys_menus::Model>> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _, QueryOrder as _};
    sys_menus::Entity::find()
        .filter(sys_menus::Column::Status.eq("ON"))
        .order_by_desc(sys_menus::Column::Id)
        .all(db)
        .await
        .map_err(db_status)
}

/// The enabled apis, ordered by operation id.
pub async fn apis_enabled_by_operation(
    db: &DatabaseConnection,
) -> StatusResult<Vec<sys_apis::Model>> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _, QueryOrder as _};
    sys_apis::Entity::find()
        .filter(sys_apis::Column::Status.eq("ON"))
        .order_by_asc(sys_apis::Column::Operation)
        .all(db)
        .await
        .map_err(db_status)
}

/// The derived-table sweep that follows TruncateBizPermissions (the
/// seeded permission ids 1..3 survive, per the reference).
async fn clean_derived_tables(db: &DatabaseConnection) {
    use sea_orm::{ColumnTrait as _, QueryFilter as _};
    let _ = sys_permission_apis::Entity::delete_many()
        .filter(sys_permission_apis::Column::PermissionId.is_not_in([1, 2, 3]))
        .exec(db)
        .await;
    let _ = sys_permission_menus::Entity::delete_many()
        .filter(sys_permission_menus::Column::PermissionId.is_not_in([1, 2, 3]))
        .exec(db)
        .await;
}

/// TruncateBizPermissions — every non-`sys:` permission, plus its
/// derived api/menu rows (whose failures the reference swallows).
pub async fn truncate_biz_permissions(db: &DatabaseConnection) -> StatusResult<()> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _};
    sys_permissions::Entity::delete_many()
        .filter(sys_permissions::Column::Code.not_like("sys:%"))
        .exec(db)
        .await
        .map_err(db_status)?;
    clean_derived_tables(db).await;
    Ok(())
}

/// TruncateBizGroup — every permission group outside the system
/// module.
pub async fn truncate_biz_groups(db: &DatabaseConnection) -> StatusResult<()> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _};
    sys_permission_groups::Entity::delete_many()
        .filter(sys_permission_groups::Column::Module.is_not_in(["sys"]))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

/// BatchCreate for permission groups (ids back in order).
pub async fn insert_permission_groups_bulk(
    db: &DatabaseConnection,
    items: Vec<sys_permission_groups::ActiveModel>,
) -> StatusResult<Vec<sys_permission_groups::Model>> {
    use sea_orm::EntityTrait as _;
    sys_permission_groups::Entity::insert_many(items)
        .exec_with_returning(db)
        .await
        .map_err(db_status)
}

/// BatchCreate for permissions (ids back in order).
pub async fn insert_permissions_bulk(
    db: &DatabaseConnection,
    items: Vec<sys_permissions::ActiveModel>,
) -> StatusResult<Vec<sys_permissions::Model>> {
    use sea_orm::EntityTrait as _;
    sys_permissions::Entity::insert_many(items)
        .exec_with_returning(db)
        .await
        .map_err(db_status)
}

/// AssignApis — one row per api, conflicts ignored.
pub async fn assign_permission_apis(
    db: &DatabaseConnection,
    permission_id: i64,
    api_ids: &[i64],
) -> StatusResult<()> {
    for api_id in api_ids {
        sys_permission_apis::Entity::insert(sys_permission_apis::ActiveModel {
            tenant_id: Set(Some(0)),
            permission_id: Set(permission_id),
            api_id: Set(*api_id),
            created_at: Set(Some(store::now())),
            ..Default::default()
        })
        .on_conflict_do_nothing_on([
            sys_permission_apis::Column::PermissionId,
            sys_permission_apis::Column::ApiId,
        ])
        .exec(db)
        .await
        .map_err(db_status)?;
    }
    Ok(())
}

/// AssignMenus — one row per menu, conflicts ignored.
pub async fn assign_permission_menus(
    db: &DatabaseConnection,
    permission_id: i64,
    menu_ids: &[i64],
) -> StatusResult<()> {
    for menu_id in menu_ids {
        sys_permission_menus::Entity::insert(sys_permission_menus::ActiveModel {
            tenant_id: Set(Some(0)),
            permission_id: Set(permission_id),
            menu_id: Set(*menu_id),
            created_at: Set(Some(store::now())),
            ..Default::default()
        })
        .on_conflict_do_nothing_on([
            sys_permission_menus::Column::PermissionId,
            sys_permission_menus::Column::MenuId,
        ])
        .exec(db)
        .await
        .map_err(db_status)?;
    }
    Ok(())
}
