//! permissionRepo — the data layer of the permission domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{sys_apis, sys_menus, sys_permission_groups, sys_permissions};

pub async fn menus_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_menus::Model> {
    sys_menus::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("menus"))
}

pub async fn insert_menus(
    db: &DatabaseConnection,
    a: sys_menus::ActiveModel,
) -> StatusResult<sys_menus::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_menus(
    db: &DatabaseConnection,
    a: sys_menus::ActiveModel,
) -> StatusResult<sys_menus::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_menus(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_menus::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn apis_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_apis::Model> {
    sys_apis::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("apis"))
}

pub async fn insert_apis(
    db: &DatabaseConnection,
    a: sys_apis::ActiveModel,
) -> StatusResult<sys_apis::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_apis(
    db: &DatabaseConnection,
    a: sys_apis::ActiveModel,
) -> StatusResult<sys_apis::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_apis(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_apis::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn permission_groups_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_permission_groups::Model> {
    sys_permission_groups::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("permission groups"))
}

pub async fn insert_permission_groups(
    db: &DatabaseConnection,
    a: sys_permission_groups::ActiveModel,
) -> StatusResult<sys_permission_groups::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_permission_groups(
    db: &DatabaseConnection,
    a: sys_permission_groups::ActiveModel,
) -> StatusResult<sys_permission_groups::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_permission_groups(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_permission_groups::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn permissions_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_permissions::Model> {
    sys_permissions::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("permissions"))
}

pub async fn insert_permissions(
    db: &DatabaseConnection,
    a: sys_permissions::ActiveModel,
) -> StatusResult<sys_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_permissions(
    db: &DatabaseConnection,
    a: sys_permissions::ActiveModel,
) -> StatusResult<sys_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_permissions(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_permissions::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
