//! The `permission_api` repository (the reference's permission_api_repo.go).

//! permissionRepo — the data layer of the permission domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait, Set};

use crate::state::{db_status, StatusResult};
use store::entities::sys_permission_apis;

// ── domain-specific queries ─────────────────────────────────────────

// ── the sync face's rebuild pipeline ────────────────────────────────

/// AssignApis — one row per api, conflicts ignored.
pub async fn assign_permission_apis(
    db: &DatabaseConnection,
    permission_id: i64,
    api_ids: &[i64],
) -> StatusResult<()> {
    for api_id in api_ids {
        sys_permission_apis::Entity::insert(sys_permission_apis::ActiveModel {
            tenant_id: Set(Some(0)),
            permission_id: Set(permission_id),
            api_id: Set(*api_id),
            created_at: Set(Some(store::now())),
            ..Default::default()
        })
        .on_conflict_do_nothing_on([
            sys_permission_apis::Column::PermissionId,
            sys_permission_apis::Column::ApiId,
        ])
        .exec(db)
        .await
        .map_err(db_status)?;
    }
    Ok(())
}
