//! The `permission` repository (the reference's permission_repo.go).

//! permissionRepo — the data layer of the permission domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{
    sys_permission_apis, sys_permission_menus,
    sys_permissions,
};

















// ── domain-specific queries ─────────────────────────────────────────


// ── the sync face's rebuild pipeline ────────────────────────────────

pub async fn permissions_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_permissions::Model> {
    sys_permissions::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("permissions"))
}
pub async fn insert_permissions(
    db: &DatabaseConnection,
    a: sys_permissions::ActiveModel,
) -> StatusResult<sys_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_permissions(
    db: &DatabaseConnection,
    a: sys_permissions::ActiveModel,
) -> StatusResult<sys_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_permissions(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_permissions::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// The derived-table sweep that follows TruncateBizPermissions (the
/// seeded permission ids 1..3 survive, per the reference).
async fn clean_derived_tables(db: &DatabaseConnection) {
    use sea_orm::{ColumnTrait as _, QueryFilter as _};
    let _ = sys_permission_apis::Entity::delete_many()
        .filter(sys_permission_apis::Column::PermissionId.is_not_in([1, 2, 3]))
        .exec(db)
        .await;
    let _ = sys_permission_menus::Entity::delete_many()
        .filter(sys_permission_menus::Column::PermissionId.is_not_in([1, 2, 3]))
        .exec(db)
        .await;
}
/// TruncateBizPermissions — every non-`sys:` permission, plus its
/// derived api/menu rows (whose failures the reference swallows).
pub async fn truncate_biz_permissions(db: &DatabaseConnection) -> StatusResult<()> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _};
    sys_permissions::Entity::delete_many()
        .filter(sys_permissions::Column::Code.not_like("sys:%"))
        .exec(db)
        .await
        .map_err(db_status)?;
    clean_derived_tables(db).await;
    Ok(())
}
/// BatchCreate for permissions (ids back in order).
pub async fn insert_permissions_bulk(
    db: &DatabaseConnection,
    items: Vec<sys_permissions::ActiveModel>,
) -> StatusResult<Vec<sys_permissions::Model>> {
    use sea_orm::EntityTrait as _;
    sys_permissions::Entity::insert_many(items)
        .exec_with_returning(db)
        .await
        .map_err(db_status)
}
