//! The `permission_group` repository (the reference's permission_group_repo.go).

//! permissionRepo — the data layer of the permission domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_permission_groups;

















// ── domain-specific queries ─────────────────────────────────────────


// ── the sync face's rebuild pipeline ────────────────────────────────

pub async fn permission_groups_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_permission_groups::Model> {
    sys_permission_groups::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("permission groups"))
}
pub async fn insert_permission_groups(
    db: &DatabaseConnection,
    a: sys_permission_groups::ActiveModel,
) -> StatusResult<sys_permission_groups::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_permission_groups(
    db: &DatabaseConnection,
    a: sys_permission_groups::ActiveModel,
) -> StatusResult<sys_permission_groups::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_permission_groups(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_permission_groups::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// TruncateBizGroup — every permission group outside the system
/// module.
pub async fn truncate_biz_groups(db: &DatabaseConnection) -> StatusResult<()> {
    use sea_orm::{ColumnTrait as _, QueryFilter as _};
    sys_permission_groups::Entity::delete_many()
        .filter(sys_permission_groups::Column::Module.is_not_in(["sys"]))
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// BatchCreate for permission groups (ids back in order).
pub async fn insert_permission_groups_bulk(
    db: &DatabaseConnection,
    items: Vec<sys_permission_groups::ActiveModel>,
) -> StatusResult<Vec<sys_permission_groups::Model>> {
    use sea_orm::EntityTrait as _;
    sys_permission_groups::Entity::insert_many(items)
        .exec_with_returning(db)
        .await
        .map_err(db_status)
}
