//! The `permission_menu` repository (the reference's permission_menu_repo.go).

//! permissionRepo — the data layer of the permission domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait, Set};

use crate::state::{db_status, StatusResult};
use store::entities::sys_permission_menus;

















// ── domain-specific queries ─────────────────────────────────────────


// ── the sync face's rebuild pipeline ────────────────────────────────

/// AssignMenus — one row per menu, conflicts ignored.
pub async fn assign_permission_menus(
    db: &DatabaseConnection,
    permission_id: i64,
    menu_ids: &[i64],
) -> StatusResult<()> {
    for menu_id in menu_ids {
        sys_permission_menus::Entity::insert(sys_permission_menus::ActiveModel {
            tenant_id: Set(Some(0)),
            permission_id: Set(permission_id),
            menu_id: Set(*menu_id),
            created_at: Set(Some(store::now())),
            ..Default::default()
        })
        .on_conflict_do_nothing_on([
            sys_permission_menus::Column::PermissionId,
            sys_permission_menus::Column::MenuId,
        ])
        .exec(db)
        .await
        .map_err(db_status)?;
    }
    Ok(())
}
