//! The `position` repository (the reference's position_repo.go).

//! miscRepo — the data layer of the misc domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_positions;

pub async fn positions_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_positions::Model> {
    sys_positions::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("positions"))
}
pub async fn insert_positions(
    db: &DatabaseConnection,
    a: sys_positions::ActiveModel,
) -> StatusResult<sys_positions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_positions(
    db: &DatabaseConnection,
    a: sys_positions::ActiveModel,
) -> StatusResult<sys_positions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_positions(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_positions::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
