//! The `role_metadata` repository (the reference's role_metadata_repo.go).

//! identityRepo — the data layer of the identity domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait as _, DatabaseConnection, EntityTrait, QueryFilter as _};

use crate::state::{db_status, StatusResult};
use store::entities::sys_role_metadata;

// ── domain-specific queries ─────────────────────────────────────────
// (the role/user-role read helpers behind RoleService — the port of the
// reference's role_repo / user_role_repo query faces)

/// The role-metadata row of one role (roleMetadataRepo.Get); `None`
/// when the role carries no metadata row.
pub async fn role_metadata_by_role_id(
    db: &DatabaseConnection,
    role_id: i64,
) -> StatusResult<Option<sys_role_metadata::Model>> {
    sys_role_metadata::Entity::find()
        .filter(sys_role_metadata::Column::RoleId.eq(role_id))
        .one(db)
        .await
        .map_err(db_status)
}
