//! The `role` repository (the reference's role_repo.go).

//! identityRepo — the data layer of the identity domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait as _, DatabaseConnection, EntityTrait, QueryFilter as _};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_roles;

























// ── domain-specific queries ─────────────────────────────────────────
// (the role/user-role read helpers behind RoleService — the port of the
// reference's role_repo / user_role_repo query faces)

pub async fn roles_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_roles::Model> {
    sys_roles::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("roles"))
}
pub async fn insert_roles(
    db: &DatabaseConnection,
    a: sys_roles::ActiveModel,
) -> StatusResult<sys_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_roles(
    db: &DatabaseConnection,
    a: sys_roles::ActiveModel,
) -> StatusResult<sys_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_roles(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_roles::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// Role codes by role ids (ListRoleCodesByRoleIds); empty in, empty out.
pub async fn role_codes_by_ids(
    db: &DatabaseConnection,
    role_ids: &[i64],
) -> StatusResult<Vec<String>> {
    if role_ids.is_empty() {
        return Ok(Vec::new());
    }
    let rows = sys_roles::Entity::find()
        .filter(sys_roles::Column::Id.is_in(role_ids.to_vec()))
        .all(db)
        .await
        .map_err(db_status)?;
    Ok(rows.into_iter().filter_map(|r| r.code).collect())
}
/// Role ids by role codes inside one tenant (ListRoleIDsByRoleCodes).
/// `role.code` is unique only per (tenant_id, code), so the caller
/// enforces the tenant scope the reference requires (tid > 0).
pub async fn role_ids_by_codes(
    db: &DatabaseConnection,
    codes: &[String],
    tenant_id: i64,
) -> StatusResult<Vec<i64>> {
    if codes.is_empty() {
        return Ok(Vec::new());
    }
    let rows = sys_roles::Entity::find()
        .filter(
            sea_orm::Condition::all()
                .add(sys_roles::Column::Code.is_in(codes.to_vec()))
                .add(sys_roles::Column::TenantId.eq(tenant_id)),
        )
        .all(db)
        .await
        .map_err(db_status)?;
    Ok(rows.into_iter().map(|r| r.id).collect())
}
