//! The `role_permission` repository (the reference's role_permission_repo.go).

//! identityRepo — the data layer of the identity domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait as _, DatabaseConnection, EntityTrait, QueryFilter as _};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_role_permissions;

// ── domain-specific queries ─────────────────────────────────────────
// (the role/user-role read helpers behind RoleService — the port of the
// reference's role_repo / user_role_repo query faces)

pub async fn role_permissions_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_role_permissions::Model> {
    sys_role_permissions::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("role permissions"))
}
pub async fn insert_role_permissions(
    db: &DatabaseConnection,
    a: sys_role_permissions::ActiveModel,
) -> StatusResult<sys_role_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_role_permissions(
    db: &DatabaseConnection,
    a: sys_role_permissions::ActiveModel,
) -> StatusResult<sys_role_permissions::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_role_permissions(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_role_permissions::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// Permission ids bound to the given role ids (ListPermissionIDsByRoleIDs).
pub async fn permission_ids_by_role_ids(
    db: &DatabaseConnection,
    role_ids: &[i64],
) -> StatusResult<Vec<i64>> {
    if role_ids.is_empty() {
        return Ok(Vec::new());
    }
    let rows = sys_role_permissions::Entity::find()
        .filter(sys_role_permissions::Column::RoleId.is_in(role_ids.to_vec()))
        .all(db)
        .await
        .map_err(db_status)?;
    Ok(rows.into_iter().map(|r| r.permission_id).collect())
}
