//! siteRepo — the data layer of the site domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{navigation_items, navigations, site_settings, sites};

pub async fn sites_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sites::Model> {
    sites::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("sites"))
}

pub async fn insert_sites(
    db: &DatabaseConnection,
    a: sites::ActiveModel,
) -> StatusResult<sites::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_sites(
    db: &DatabaseConnection,
    a: sites::ActiveModel,
) -> StatusResult<sites::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_sites(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sites::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn site_settings_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<site_settings::Model> {
    site_settings::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("site settings"))
}

pub async fn insert_site_settings(
    db: &DatabaseConnection,
    a: site_settings::ActiveModel,
) -> StatusResult<site_settings::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_site_settings(
    db: &DatabaseConnection,
    a: site_settings::ActiveModel,
) -> StatusResult<site_settings::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_site_settings(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    site_settings::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn navigations_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<navigations::Model> {
    navigations::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("navigations"))
}

pub async fn insert_navigations(
    db: &DatabaseConnection,
    a: navigations::ActiveModel,
) -> StatusResult<navigations::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_navigations(
    db: &DatabaseConnection,
    a: navigations::ActiveModel,
) -> StatusResult<navigations::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_navigations(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    navigations::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn navigation_items_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<navigation_items::Model> {
    navigation_items::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("navigation items"))
}

pub async fn insert_navigation_items(
    db: &DatabaseConnection,
    a: navigation_items::ActiveModel,
) -> StatusResult<navigation_items::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_navigation_items(
    db: &DatabaseConnection,
    a: navigation_items::ActiveModel,
) -> StatusResult<navigation_items::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_navigation_items(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    navigation_items::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
