//! The `site` repository (the reference's site_repo.go).

//! siteRepo — the data layer of the site domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sites;

pub async fn sites_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sites::Model> {
    sites::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("sites"))
}
pub async fn insert_sites(
    db: &DatabaseConnection,
    a: sites::ActiveModel,
) -> StatusResult<sites::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_sites(
    db: &DatabaseConnection,
    a: sites::ActiveModel,
) -> StatusResult<sites::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_sites(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sites::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
