//! socialRepo — the data layer of the social domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::{comments, interaction_counters, post_likes, post_watches};

pub async fn comments_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<comments::Model> {
    comments::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("comments"))
}

pub async fn insert_comments(
    db: &DatabaseConnection,
    a: comments::ActiveModel,
) -> StatusResult<comments::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_comments(
    db: &DatabaseConnection,
    a: comments::ActiveModel,
) -> StatusResult<comments::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_comments(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    comments::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn interaction_counters_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<interaction_counters::Model> {
    interaction_counters::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("interaction counters"))
}

pub async fn insert_interaction_counters(
    db: &DatabaseConnection,
    a: interaction_counters::ActiveModel,
) -> StatusResult<interaction_counters::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_interaction_counters(
    db: &DatabaseConnection,
    a: interaction_counters::ActiveModel,
) -> StatusResult<interaction_counters::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_interaction_counters(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    interaction_counters::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn post_likes_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<post_likes::Model> {
    post_likes::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("post likes"))
}

pub async fn insert_post_likes(
    db: &DatabaseConnection,
    a: post_likes::ActiveModel,
) -> StatusResult<post_likes::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_post_likes(
    db: &DatabaseConnection,
    a: post_likes::ActiveModel,
) -> StatusResult<post_likes::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_post_likes(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    post_likes::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}

pub async fn post_watches_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<post_watches::Model> {
    post_watches::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("post watches"))
}

pub async fn insert_post_watches(
    db: &DatabaseConnection,
    a: post_watches::ActiveModel,
) -> StatusResult<post_watches::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_post_watches(
    db: &DatabaseConnection,
    a: post_watches::ActiveModel,
) -> StatusResult<post_watches::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_post_watches(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    post_watches::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
