//! storageRepo — the data layer of the storage domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::files;

pub async fn files_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<files::Model> {
    files::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("files"))
}

pub async fn insert_files(
    db: &DatabaseConnection,
    a: files::ActiveModel,
) -> StatusResult<files::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}

pub async fn update_files(
    db: &DatabaseConnection,
    a: files::ActiveModel,
) -> StatusResult<files::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}

pub async fn delete_files(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    files::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
