//! The `task` repository (the reference's task_repo.go).

//! messagingRepo — the data layer of the messaging domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait, DatabaseConnection, EntityTrait, QueryFilter};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_tasks;













// ── domain-specific queries ──────────────────────────────────────────

pub async fn tasks_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_tasks::Model> {
    sys_tasks::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("tasks"))
}
pub async fn insert_tasks(
    db: &DatabaseConnection,
    a: sys_tasks::ActiveModel,
) -> StatusResult<sys_tasks::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_tasks(
    db: &DatabaseConnection,
    a: sys_tasks::ActiveModel,
) -> StatusResult<sys_tasks::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_tasks(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_tasks::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// The (tenant_id, type_name) lookup of the reference's Get-by-TypeName
/// (unique within a tenant).
pub async fn task_by_type_name(
    db: &DatabaseConnection,
    type_name: &str,
    tenant_id: i64,
) -> StatusResult<Option<sys_tasks::Model>> {
    sys_tasks::Entity::find()
        .filter(sys_tasks::Column::TypeName.eq(type_name))
        .filter(sys_tasks::Column::TenantId.eq(tenant_id))
        .one(db)
        .await
        .map_err(db_status)
}
/// The reference's tenant-scoped bulk delete of a task (a silent no-op on
/// missing rows, like the reference's `Delete().Where().Exec`).
pub async fn delete_task_scoped(
    db: &DatabaseConnection,
    id: i64,
    tenant_id: Option<i64>,
) -> StatusResult<()> {
    let mut del = sys_tasks::Entity::delete_many().filter(sys_tasks::Column::Id.eq(id));
    if let Some(tid) = tenant_id {
        del = del.filter(sys_tasks::Column::TenantId.eq(tid));
    }
    del.exec(db).await.map_err(db_status)?;
    Ok(())
}
