//! The `user` repository (the reference's user_repo.go).

//! identityRepo — the data layer of the identity domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{DatabaseConnection, EntityTrait};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_users;

























// ── domain-specific queries ─────────────────────────────────────────
// (the role/user-role read helpers behind RoleService — the port of the
// reference's role_repo / user_role_repo query faces)

pub async fn users_by_id(db: &DatabaseConnection, id: i64) -> StatusResult<sys_users::Model> {
    sys_users::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("users"))
}
pub async fn insert_users(
    db: &DatabaseConnection,
    a: sys_users::ActiveModel,
) -> StatusResult<sys_users::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_users(
    db: &DatabaseConnection,
    a: sys_users::ActiveModel,
) -> StatusResult<sys_users::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_users(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_users::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
