//! The `user_role` repository (the reference's user_role_repo.go).

//! identityRepo — the data layer of the identity domain (generated by
//! scripts/gen-repos.py; domain-specific queries live at the tail).

use sea_orm::{ColumnTrait as _, DatabaseConnection, EntityTrait, QueryFilter as _};

use crate::state::{db_status, not_found_status, StatusResult};
use store::entities::sys_user_roles;

// ── domain-specific queries ─────────────────────────────────────────
// (the role/user-role read helpers behind RoleService — the port of the
// reference's role_repo / user_role_repo query faces)

pub async fn user_roles_by_id(
    db: &DatabaseConnection,
    id: i64,
) -> StatusResult<sys_user_roles::Model> {
    sys_user_roles::Entity::find_by_id(id)
        .one(db)
        .await
        .map_err(db_status)?
        .ok_or_else(|| not_found_status("user roles"))
}
pub async fn insert_user_roles(
    db: &DatabaseConnection,
    a: sys_user_roles::ActiveModel,
) -> StatusResult<sys_user_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.insert(db).await.map_err(db_status)
}
pub async fn update_user_roles(
    db: &DatabaseConnection,
    a: sys_user_roles::ActiveModel,
) -> StatusResult<sys_user_roles::Model> {
    use sea_orm::ActiveModelTrait as _;
    a.update(db).await.map_err(db_status)
}
pub async fn delete_user_roles(db: &DatabaseConnection, id: i64) -> StatusResult<()> {
    sys_user_roles::Entity::delete_by_id(id)
        .exec(db)
        .await
        .map_err(db_status)?;
    Ok(())
}
/// The user's role ids (ListRoleIDs). `include_expired` keeps bindings
/// past their `end_at` — the reference filters them unless asked to.
pub async fn user_role_ids(
    db: &DatabaseConnection,
    user_id: i64,
    include_expired: bool,
) -> StatusResult<Vec<i64>> {
    if user_id == 0 {
        return Ok(Vec::new());
    }
    Ok(user_roles_by_user_id(db, user_id, include_expired)
        .await?
        .into_iter()
        .map(|r| r.role_id)
        .collect())
}
/// The user's role binding rows (ListByUserID), newest-binding order is
/// the table order; expired rows dropped unless `include_expired`.
pub async fn user_roles_by_user_id(
    db: &DatabaseConnection,
    user_id: i64,
    include_expired: bool,
) -> StatusResult<Vec<sys_user_roles::Model>> {
    if user_id == 0 {
        return Ok(Vec::new());
    }
    let mut query =
        sys_user_roles::Entity::find().filter(sys_user_roles::Column::UserId.eq(user_id));
    if !include_expired {
        query = query.filter(
            sea_orm::Condition::any()
                .add(sys_user_roles::Column::EndAt.is_null())
                .add(sys_user_roles::Column::EndAt.gt(store::now())),
        );
    }
    query.all(db).await.map_err(db_status)
}
