
-- 菜单种子（对齐 admin-react 路由树：业务路由 modules/*.tsx 的目录/页面两级结构）
INSERT INTO public.sys_menus (id, tenant_id, parent_id, "type", name, path, component, meta, status, created_at)
SELECT v.id, 0, v.parent_id, v.type, v.name, v.path, v.component, v.meta::jsonb, 'ON', now()
FROM (VALUES
    (1, NULL, 'CATALOG', 'Dashboard', '/dashboard', 'BasicLayout', '{"title":"仪表盘","icon":"lucide:layout-dashboard","order":0}'),
    (2, 1, 'MENU', 'Analytics', '/analytics', 'dashboard/analytics/index', '{"title":"分析页","icon":"lucide:area-chart","order":0}'),
    (10, NULL, 'CATALOG', 'Content', '/content', 'BasicLayout', '{"title":"内容管理","icon":"lucide:file-text","order":1}'),
    (11, 10, 'MENU', 'Posts', '/content/posts', 'content/posts/index', '{"title":"文章管理","icon":"lucide:newspaper","order":0}'),
    (12, 10, 'MENU', 'Categories', '/content/categories', 'content/categories/index', '{"title":"分类管理","icon":"lucide:folder-tree","order":1}'),
    (13, 10, 'MENU', 'Tags', '/content/tags', 'content/tags/index', '{"title":"标签管理","icon":"lucide:tags","order":2}'),
    (14, 10, 'MENU', 'Pages', '/content/pages', 'content/pages/index', '{"title":"页面管理","icon":"lucide:files","order":3}'),
    (15, 10, 'MENU', 'Models', '/content/models', 'content/models/index', '{"title":"内容模型","icon":"lucide:boxes","order":4}'),
    (20, NULL, 'CATALOG', 'Engagement', '/engagement', 'BasicLayout', '{"title":"互动管理","icon":"lucide:message-circle","order":2}'),
    (21, 20, 'MENU', 'Comments', '/engagement/comments', 'engagement/comments/index', '{"title":"评论管理","icon":"lucide:message-square","order":0}'),
    (30, NULL, 'CATALOG', 'Media', '/media', 'BasicLayout', '{"title":"媒体资产","icon":"lucide:image","order":3}'),
    (31, 30, 'MENU', 'MediaAssets', '/media/media-assets', 'media/media-assets/index', '{"title":"媒体库","icon":"lucide:images","order":0}'),
    (40, NULL, 'CATALOG', 'SiteSetting', '/site-setting', 'BasicLayout', '{"title":"站点设置","icon":"lucide:globe","order":4}'),
    (41, 40, 'MENU', 'Sites', '/site-setting/sites', 'site-setting/sites/index', '{"title":"站点管理","icon":"lucide:server","order":0}'),
    (42, 40, 'MENU', 'SiteSettings', '/site-setting/site-settings', 'site-setting/site-settings/index', '{"title":"配置管理","icon":"lucide:settings","order":1}'),
    (43, 40, 'MENU', 'Navigations', '/site-setting/navigations', 'site-setting/navigations/index', '{"title":"导航管理","icon":"lucide:compass","order":2}'),
    (50, NULL, 'CATALOG', 'Opm', '/opm', 'BasicLayout', '{"title":"组织人员","icon":"lucide:users","order":5}'),
    (51, 50, 'MENU', 'Users', '/opm/users', 'opm/users/index', '{"title":"用户管理","icon":"lucide:user","order":0}'),
    (52, 50, 'MENU', 'OrgUnits', '/opm/org-units', 'opm/org-units/index', '{"title":"组织架构","icon":"lucide:network","order":1}'),
    (53, 50, 'MENU', 'Positions', '/opm/positions', 'opm/positions/index', '{"title":"职位管理","icon":"lucide:briefcase","order":2}'),
    (54, 50, 'MENU', 'Profile', '/opm/profile', 'opm/profile/index', '{"title":"个人中心","icon":"lucide:user-pen","order":3}'),
    (60, NULL, 'CATALOG', 'Permission', '/permission', 'BasicLayout', '{"title":"权限管理","icon":"lucide:shield","order":6}'),
    (61, 60, 'MENU', 'Roles', '/permission/roles', 'permission/roles/index', '{"title":"角色管理","icon":"lucide:key","order":0}'),
    (62, 60, 'MENU', 'Menus', '/permission/menus', 'permission/menus/index', '{"title":"菜单管理","icon":"lucide:menu","order":1}'),
    (63, 60, 'MENU', 'Apis', '/permission/apis', 'permission/apis/index', '{"title":"接口管理","icon":"lucide:plug","order":2}'),
    (64, 60, 'MENU', 'Codes', '/permission/codes', 'permission/codes/index', '{"title":"权限点","icon":"lucide:lock","order":3}'),
    (70, NULL, 'CATALOG', 'System', '/system', 'BasicLayout', '{"title":"系统管理","icon":"lucide:settings-2","order":7}'),
    (71, 70, 'MENU', 'Dict', '/system/dict', 'system/dict/index', '{"title":"字典管理","icon":"lucide:book","order":0}'),
    (72, 70, 'MENU', 'Languages', '/system/languages', 'system/languages/index', '{"title":"语言管理","icon":"lucide:languages","order":1}'),
    (73, 70, 'MENU', 'Tasks', '/system/tasks', 'system/tasks/index', '{"title":"任务调度","icon":"lucide:clock","order":2}'),
    (74, 70, 'MENU', 'Files', '/system/files', 'system/files/index', '{"title":"文件管理","icon":"lucide:folder","order":3}'),
    (75, 70, 'MENU', 'LoginPolicies', '/system/login-policies', 'system/login-policies/index', '{"title":"登录策略","icon":"lucide:shield-alert","order":4}'),
    (80, NULL, 'CATALOG', 'InternalMessage', '/internal-message', 'BasicLayout', '{"title":"消息中心","icon":"lucide:bell","order":8}'),
    (81, 80, 'MENU', 'Inbox', '/internal-message/inbox', 'internal-message/inbox/index', '{"title":"收件箱","icon":"lucide:inbox","order":0}'),
    (82, 80, 'MENU', 'Messages', '/internal-message/messages', 'internal-message/messages/index', '{"title":"消息管理","icon":"lucide:mail","order":1}'),
    (83, 80, 'MENU', 'MsgCategories', '/internal-message/categories', 'internal-message/categories/index', '{"title":"消息分类","icon":"lucide:tag","order":2}'),
    (90, NULL, 'CATALOG', 'Log', '/log', 'BasicLayout', '{"title":"审计日志","icon":"lucide:scroll-text","order":9}'),
    (91, 90, 'MENU', 'LoginAuditLogs', '/log/login-audit-logs', 'log/login-audit-logs/index', '{"title":"登录日志","icon":"lucide:log-in","order":0}'),
    (92, 90, 'MENU', 'ApiAuditLogs', '/log/api-audit-logs', 'log/api-audit-logs/index', '{"title":"API 日志","icon":"lucide:activity","order":1}'),
    (93, 90, 'MENU', 'OperationAuditLogs', '/log/operation-audit-logs', 'log/operation-audit-logs/index', '{"title":"操作日志","icon":"lucide:pen-line","order":2}'),
    (94, 90, 'MENU', 'DataAccessAuditLogs', '/log/data-access-audit-logs', 'log/data-access-audit-logs/index', '{"title":"数据日志","icon":"lucide:database","order":3}'),
    (95, 90, 'MENU', 'PermissionAuditLogs', '/log/permission-audit-logs', 'log/permission-audit-logs/index', '{"title":"权限日志","icon":"lucide:user-check","order":4}'),
    (96, 90, 'MENU', 'PolicyEvaluationLogs', '/log/policy-evaluation-logs', 'log/policy-evaluation-logs/index', '{"title":"策略日志","icon":"lucide:git-branch","order":5}'),
    (100, NULL, 'CATALOG', 'Tenant', '/tenant', 'BasicLayout', '{"title":"租户管理","icon":"lucide:building","order":10}'),
    (101, 100, 'MENU', 'Members', '/tenant/members', 'tenant/members/index', '{"title":"成员管理","icon":"lucide:users-round","order":0}')
) AS v(id, parent_id, type, name, path, component, meta)
WHERE NOT EXISTS (SELECT 1 FROM public.sys_menus);
