allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  msw: set this to true or false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - sharp
  - unrs-resolver
