// This file is auto-generated by protoc-gen-typescript-http and should not be edited manually.
export * from "./generated/app/service/v1/index";

// ApiClient 单例
export { apiClient } from "./client";

// Composables 层 - Vue Query 集成（useXxx Hook + fetchXxx 方法）
export * from "./composables";
