allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  '@tarojs/binding': false
  '@tarojs/cli': false
  core-js: false
  core-js-pure: false
  esbuild: false
  micromark: false
  unrs-resolver: set this to true or false
  weapp-tailwindcss: false
